### ISSUE TITLE
更新版本 3.6.3 clone 已经可用。

### ISSUE THREAD

**Issue by shangkedada** [SteveZMTstudios/Phigros-history#13]
### Phigros共存版已经发布。

最新版本: `3.6.3 clone`

网盘地址:
```URL
https://pan.baidu.com/s/1q34eQhBkSnRLdAq6MqfYiA?pwd=363c 

```

@SteveZMTstudios

**Comment by shangkedada** [comment]
除此之外还有愚人节版本暂未共存

**Comment by shangkedada** [comment]
还待添加的如下![Screenshot_20240622_214021_edit_46950152929293.jpg](https://github.com/SteveZMTstudios/Phigros-history/assets/83653687/9ca11720-e602-4a23-8a5a-9ddbf4e68cf3)

**Comment by SteveZMTstudios** [comment]
3.6.3 taptap版本已经在releases中。

**Comment by SteveZMTstudios** [comment]
出于 DMCA 并且已经收到类似的警告,共存版可能不会再更新。请考虑使用光速虚拟机等虚拟机软件，或者亲自使用Apk Editor Pro等工具来共存。

**Comment by SteveZMTstudios** [comment]
为方便其他用户使用您的版本，该issue将被保留，但是将被设置为关闭状态。

**Comment by shangkedada** [comment]
该版本是使用MT管理器手动共存并更改签名的

**Comment by SteveZMTstudios** [comment]
问题不只是修改。用户可以自己下载相应的apk,但是如果是我修改（作为一个分发者）那么我可能涉嫌修改软件并侵害软件著作权;或者是修改的软件存在病毒而无法被感知。这不属于作品的合理使用(lsh原话）。但是如果由用户亲自修改则不存在这种问题。2024年6月23日 05:18，shangkedada ***@***.***>写道：
该版本是使用MT管理器手动共存并更改签名的

**Comment by shangkedada** [comment]
OK明白了
