### ISSUE TITLE
更新版本 3.7.0 已经可用。

### ISSUE THREAD

**Issue by SoSlowA** [SteveZMTstudios/Phigros-history#14]
### Phigros新版本已经发布。

最新版本: `3.7.0`

网盘地址:
```URL
https://
```

(如果有一个已经存储在网盘中的版本，请贴上它)

请尽快处理，以防版本丢失。
@SteveZMTstudios

**Comment by YimingOvO** [comment]
您好，这边项目所有者委托我来告知您，很不幸，所有者因网络原因无法登录github，导致已经传到123云盘的安装包无法同步到github，非常抱歉

**Comment by SteveZMTstudios** [comment]
https://github.com/SteveZMTstudios/Phigros-history/releases/tag/v3.7.0
