### ISSUE TITLE
有无限刷mb的那个版本吗

### ISSUE THREAD

**Issue by shaddy1520** [SteveZMTstudios/Phigros-history#19]
听说是1.4.3的，我找了超级久了但是没找到，已经病急乱投医到这来了（😭）

**Comment by SteveZMTstudios** [comment]
额，我记得那个是外挂吧...
或者说破解版？

~~加钱我帮你打MB（~~

**Comment by shaddy1520** [comment]
emmm，不是的，是官方自己的bug，打一次教程出32mb，现在已经找到啦> 额，我记得那个是外挂吧...
> 或者说破解版？
> 
> ~~加钱我帮你打MB（~~

**Comment by SteveZMTstudios** [comment]
@shaddy1520 那我没听说过（（
