### ISSUE TITLE
v3.0.0 已经被更新

### ISSUE THREAD

**Issue by ttyao0518** [SteveZMTstudios/Phigros-history#4]
Phigros更新v3.0.0辣！

**Comment by SteveZMTstudios** [comment]
在传了在传了
另外我打算传一个空的存档包，就是新章节还没有全解锁的那种
但是好像你们如果要应用备份的话，得先root🤔

**Comment by SteveZMTstudios** [comment]
> Phigros更新v3.0.0辣！

在传了在传了
另外我打算传一个空的存档包，就是新章节还没有全解锁的那种
但是好像你们如果要应用备份的话，得先root🤔

**Comment by SteveZMTstudios** [comment]
[冲！](https://github.com/SteveZMTstudios/Phigros-history/releases/tag/v3.0.0.1)

**Comment by ttyao0518** [comment]
原来你传的都是已经解锁的那种吗？
我只用它拿来解包（
其实MT管理器不用ROOT就可以提取安装包，就是得重新下一遍Phi（

发件人: ***@***.***>
发送时间: 2023年5月1日 22:15
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [SteveZMTstudios/Phigros-history] v3.0.0 已经被更新 (Issue #4)


Phigros更新v3.0.0辣！

在传了在传了
另外我打算传一个空的存档包，就是新章节还没有全解锁的那种
但是好像你们如果要应用备份的话，得先root🤔
